### ISSUE TITLE
hide tree and gallery links on large device screens

### ISSUE THREAD

**Issue by shrn-werk** [aboutcircles/nft-tree#24]
we need to remove the bottom links on the main display devices (large monitors) as we won’t be using the monitors as touch input devices.

- [x] hide `see the gallery` and `back to the tree` links on the main monitor displays
- [x] display links on mobile.

![Image](https://github.com/aboutcircles/nft-tree/assets/141832818/b8b6535e-9d5f-4aae-981f-de671550518a)
![Image](https://github.com/aboutcircles/nft-tree/assets/141832818/75e6b3dd-47c9-4eb7-80b1-febbe9f18d93)

**Comment by Wagalidoom** [comment]
Fixed. Bottom links are hidden on portrait mode for large devices.
