### ISSUE TITLE
update QR code URL

### ISSUE THREAD

**Issue by shrn-werk** [aboutcircles/nft-tree#25]
- [x] change the QR code to link to https://www.aboutcircles.com/circles-dappcon-nft so people can scan it on their mobiles to view the tree

**Comment by shrn-werk** [comment]
![Image](https://github.com/aboutcircles/nft-tree/assets/141832818/a0e0c410-c89a-4019-ba3c-581a18a00bdd)

**Comment by Wagalidoom** [comment]
Done 👍
